<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="Assets\Idol.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeLab.Application\TimeLab.Application.csproj" />
    <ProjectReference Include="..\TimeLab.Infrastructure\TimeLab.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Idol.jpg">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>TimeLab.App.Program</StartupObject>
	<ApplicationIcon>Assets\src=http___inews_32x32.ico</ApplicationIcon>
	  <Version>1.2.0</Version>
	  <AssemblyVersion>1.2.0.0</AssemblyVersion>
	  <FileVersion>1.2.0.0</FileVersion>
	  <InformationalVersion>1.2.0</InformationalVersion>
  </PropertyGroup>
	
</Project>
